#!/usr/bin/env python
import os
import re
import bottle
import json
from bottle import route, run

@route('/', method='GET')
@route('/:path', method='GET')
def get_dbs(path=""):
	whisper = "/opt/graphite/storage/whisper"
	f = []
	d = []
	if path:
		for i in path.split('+'):
			whisper += "/%s" % i
	x = os.listdir(whisper)
	for i in x:
		result = re.search("\.wsp", i)
		if result != None:
			f.append(i.split('.wsp')[0])
        	else:
                	d.append(i)
	data = {}
	data["directories"] = d
	data["databases"] = f
	data["status"] = "OK"
	return json.dumps(data)

run(host="0.0.0.0", port=19004, debug=False)
